/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `nsl' library (-lnsl). */
#define HAVE_LIBNSL 1

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the `ssl' library (-lssl). */
#define HAVE_LIBSSL 1

/* Define to 1 if you have the `sasl' library (-lsasl2). */
#define HAVE_LIBSASL 1

/* Define to 1 if `tm_zone' is member of `struct tm'. */
#define HAVE_STRUCT_TM_TM_ZONE 1

/* Define to 1 if your `struct tm' has `tm_zone'. Deprecated, use
   `HAVE_STRUCT_TM_TM_ZONE' instead. */
#define HAVE_TM_ZONE 1

/* Define to 1 if you don't have `tm_zone' but do have the external array
   `tzname'. */
/* #undef HAVE_TZNAME */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "simta@umich.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "simta"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "simta VERSION"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "simta"

/* Define to the version of this package. */
#define PACKAGE_VERSION "VERSION"

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Define to 1 if you have LDAP */
#define HAVE_LDAP 1

/* Define to 1 if you have LIBWRAP */
#define HAVE_LIBWRAP 1
