[project]
name = 'simta'
version = '0'
requires-python = '>= 3.8'
dependencies = [
    'aiosmtpd',
    'cryptography',
    'dirty-equals',
    'dnspython',
    'inline-snapshot',
    'pytest',
    'ruamel.yaml',
    'ruff',
]

[tool.inline-snapshot]
format-command='ruff format --stdin-filename {filename}'

[tool.ruff]
line-length = 160

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint]
select = ["F", "E", "W", "B", "RUF"]
