.TH simsendmail "1" "January 2003" "RSUG" "User Commands"

.SH NAME
.B simsendmail 
\- simta's sendmail interface

.SH SYNOPSIS
.B simsendmail 
[
.BI \-b\  option
] [
.B \-i
] [
.BI \-o\  option
] [
.I to-address
]
.sp
.SH DESCRIPTION

.B simsendmail
is 
.B simta's
.B sendmail
interface

simsendmail is simta's sendmail interface.  simsendmail is intended
as a replacement for sendmail in that any program that currently
uses sendmail for communication may use simsendmail instead.
simsendmail's behavior, including command line options, should be
identical to sendmail.

With no flags, simsendmail reads standard input until it reaches
either the end of file or a special marker consisting only of a
single dot on a line.  The single dot may be ignored as an end of
file marker with the -i option.   simsendmail then sends a copy of
the message found there to all of the to-addresses listed.


.sp
.SH OPTIONS
.TP 19
.BI \-b\  option
Currently ignore all -b options.
.TP 19
.B \-i
ignore a single dot on a line as an end of message marker.
.TP 19
.B \-oi
ignore a single dot on a line as an end of message marker.
.sp
.SH SEE ALSO
.BR sendmail (1)
