.Dd $Mdocdate: February 04 2016 $
.Dt SIMTA 8
.Os umich
.Sh NAME
.Nm simta
.Nd Mail Transfer Agent

.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl cCdV
.Op Fl D Ar base_directory
.Op Fl f Ar config_file
.Op Fl p Ar port
.Op Fl q | Fl Q Ar filter
.Op Fl u Ar username
.Ek

.Sh DESCRIPTION
.Nm
is a Simple Internet Mail Transfer Agent. It is designed to have
simple configuration with sane defaults, and to produce useful logs.
.Pp
.Nm
and some of its associated commands store data in directories underneath
.Ar base_directory
(which defaults to
.Pa /var/spool/simta
):
.Pp
.Bl -tag -width Ds -offset indent
.It Pa fast
Messages that are owned by a single process and might be in an
inconsistent state.
.It Pa slow
Messages that are owned by the main process and can be safely
handled by any queue runner.
.It Pa local
Messages from
.Nm simsendmail
that are waiting to be processed.
.It Pa dead
Messages that could not be processed normally.
.It Pa etc
.Nm
outputs informational files here when told to do so by
.Nm simc .
.It Pa command
.Nm simc
controls
.Nm
by creating command files in this directory.
.El
.Pp
Messages are stored as pairs of files, with metadata in
.Pa E<foo>
and the corresponding message data in
.Pa D<foo> .
Messages in the fast queue might have a temporary metadata file called
.Pa t<foo>
in place of the normal E file.

.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c
Check the configuration file for errors and exit.
.It Fl C
Clean the queues and exit.
.It Fl d
Enables debug logging.
Multiple
.Fl d
options increase the verbosity.
.It Fl D Ar base_directory
Specifies an alternate base directory.
.It Fl f Ar config_file
Specifies an alternate configuration file.
.It Fl p Ar port
Specifies an alternate port to listen on.
.It Fl q
Run through the slow queue and exit.
.It Fl Q Ar filter
Run through the specified host queue and exit.
.It Fl u Ar user
Specifies a username to run as.
.It Fl V
Display the version information and exit.
.El

.Sh SEE ALSO
.Xr simsendmail 1 ,
.Xr simta.conf 4 ,
.Xr simc 8
