.TH simta "8" "October 2004" "RSUG" "User Commands"

.SH NAME
.B simta 
\- simta daemon

.SH SYNOPSIS
.B simta
[
.B \-' '
] [
.B \-a
] [
.BI \-b\  option
] [
.B \-c
] [
.B \-C
] [
.BI \-D\  option
] [
.BI \-f\  option
] [
.B \-I
] [
.BI \-I\  option
] [
.BI \-m\  option
] [
.BI \-M\  option
] [
.BI \-p\  option
] [
.B \-q
] [
.B \-r
] [
.B \-R
] [
.BI \-s\  option
] [
.B \-V
] [
.BI \-w\  option
] [
.BI \-x\  option
] [
.BI \-y\  option
] [
.BI \-z\  option
]
.sp
.SH DESCRIPTION

.B simta
is a mailer daemon.

simsendmail(1) is simta's local entry point.  A local queue runner can
be launched with -q.

Simta reads simta.conf(4)

.sp
.SH OPTIONS
.TP 19
.B \-' '
disallow strict SMTP syntax checking for compatability with some  non-RFC
complient SMTP hosts
.TP 19
.B \-a
Disable automatic configuration based on DNS
.TP 19
.BI \-b\  backlog
Specify how many hosts we allow in the listen backlog
.TP 19
.B \-c
Don't run, only check config files
.TP 19
.B \-C
Clean simta's filesystem, don't run
.TP 19
.BI \-D\  path/to/directory
Specify simta's base directory
.TP 19
.BI \-f\  path/to/filename
specify simta's config file
.TP 19
.B \-I
Ignore the fact some hosts have a bad reverse in DNS, and still talk to them
.TP 19
.BI \-m\  connections
Specify the maximum number of connections simta will have at a given time
.TP 19
.BI \-M\  maildomain
Specify simta's mail domain
.TP 19
.BI \-p\  port
Specify which port simta will listen for TCP connection on
.TP 19
.B \-q
Just run a queue runner for the slow queue
.TP 19
.B \-r
Uses randfile for tls communication
.TP 19
.B \-R
Enable global relay
.TP 19
.BI \-s\ spooldir
Specify simta's spool directory
.TP 19
.B \-V
Give version info
.TP 19
.BI \-w\  authlevel
Set authlevel: 0:none, 1:serv, 2:client & serv
.TP 19
.BI \-x\  ca-file
Specify wich ca file to use
.TP 19
.BI \-y\  cert-file
Specify wich cert file to use
.TP 19
.BI \-z\  private_key
Specify the private key
.sp

.SH SEE ALSO
.BR simsendmail (1)
.BR simta.conf (4)
