.TH VACREPORT "8" "23 February 2005" "U-M LDAP Project" "MAINTENANCE COMMANDS"
.SH NAME
.B vacreport
\- print a report of all people on vacation
.SH SYNOPSIS
.B vacreport
[
.B \-v
.I database-directory
]
.SH DESCRIPTION
.B
vacreport
prints a report of all people who have DB files in the 
.I database-directory
.
.SH OPTIONS
.TP
.B \-v
Specify the location of the database file directory.  Default is
/var/vacationdb.
.SH FILES
.B /var/vacationdb/[a-z]/.
.SH SEE ALSO
.BR vacation(8),
.BR unvacate(8),
.BR sendmail(8),
.BR ldap(3)
.LP
.B RFC 1487
\- X.500 Lightweight Directory Access Protocol (Yeong, Howes, Kille)
.LP
.B
RFC 1488
\- The X.500 String Representation of Standard Attribute
Syntaxes (Howes, Yeong, Kille, Robbins).
.SH AUTHOR
Gordon Good, University of Michigan
