.TH SIMVACREPORT "8" "23 February 2005" "U-M LDAP Project" "MAINTENANCE COMMANDS"
.SH NAME
.B simvacreport
\- print a report of all people on vacation
.SH SYNOPSIS
.B simvacreport
[
.B \-v
.I database-directory
]
.SH DESCRIPTION
.B
simvacreport
prints a report of all people who have DB files in the 
.I database-directory
.
.SH OPTIONS
.TP
.B \-v
Specify the location of the database file directory.  Default is
/var/vacationdb.
.SH FILES
.B /var/vacationdb/[a-z]/.
.SH SEE ALSO
.BR simvacation(8),
.BR simunvacate(8),
.BR sendmail(8),
.BR ldap(3)
.LP
.B RFC 2251
\- Lightweight Directory Access Protocol (v3)
.LP

